security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GithubAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/devis/utilisateur, roles: ROLE_USER }
        - { path: ^/assistance, roles: ROLE_USER }
        - { path: ^/profil/, roles: ROLE_USER }
        - { path: ^/connect/github, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/check/github, roles: IS_AUTHENTICATED_ANONYMOUSLY }
