security:
    hide_user_not_found: false
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: Username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\GithubAuthenticator
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/devis/utilisateur, roles: ROLE_USER }
        - { path: ^/assistance, roles: ROLE_USER }
        - { path: ^/profil/, roles: ROLE_USER }
        - { path: ^/connect/github, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/github/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
