#index:
#    path: /
#    controller: App\Controller\DefaultController::index
exception:
  path: /error
  controller: App\Controller\ExceptionController::showException

front_maintenance:
    path: /maintenance
    controller: App\Controller\Front\MaintenanceController::maintenance

change_locale:
    path: /change-locale/{locale}
    controller: App\Controller\Front\LocaleController
    methods: ['GET',POST] 
    requirements:
        locale: fr|en

translate_batch:
    path: /translate-batch
    controller: App\Controller\Front\TranslationController::translateBatch
    methods: POST