#index:
#    path: /
#    controller: App\Controller\DefaultController::index
exception:
  path: /error
  controller: App\Controller\ExceptionController::showException

#front_maintenance:
    #path: /
    #controller: App\Controller\Front\MaintenanceController::maintenance