#index:
#    path: /
#    controller: App\Controller\DefaultController::index
exception:
  path: /error
  controller: App\Controller\ExceptionController::showException

front_maintenance:
    path: /maintenance
    controller: App\Controller\Front\MaintenanceController::maintenance

oauth_check:
  path: /oauth/check
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController